on:
  workflow_dispatch:
  push:
    branches: [develop]

name: "Update Transifex on Push"

jobs:
  push-translations-to-transifex:
    if: ${{ github.repository == 'DIGI-UW/OpenELIS-Global-2' }}
    name: push-translations-to-transifex

    runs-on: ubuntu-latest
    permissions:
      actions: read

    steps:
      - uses: actions/checkout@v4
      - name: Push source file using transifex client
        uses: transifex/cli-action@v2
        with:
          token: ${{ secrets.TRANSIFEX_TOKEN }}
